Repository MarcoKeppel/IngSoft2, pull requests merged in 2022-06, with the labels that each got.

#30 Gallery API fixes
  app/gallery.js
Labels: bug

#28 Added notification method
  app/models/user.js
  app/notification.js
  app/upload.js
Labels: enhancement

#41 Heroku file upload
  app/app.js
  app/image.js
  app/models/imageFile.js
  app/upload.js
  static/index.html
  static/post.html
Labels: bug

#45 Added test for following
  app/follow.js
  app/follow.test.js
Labels: devops

#43 /upload testing
  app/upload.test.js
Labels: devops

#42 /gallery testing
  app/gallery.test.js
Labels: devops
